spring:
  profiles:
    active:
    - redis

---
spring:
  profiles: redis
  application:
    name: configserver-redis
    
---
spring:
  profiles: mybatis
  application:
    name: configserver-mybatis
  datasource:
    url: jdbc://mysql://127.0.0.1:3306/newer?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
